# Generated by Django 5.2.1 on 2025-05-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studytime', models.IntegerField(verbose_name='勉強時間')),
                ('studycontent', models.TextField(verbose_name='勉強内容')),
                ('nickname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.simpleuser')),
            ],
        ),
    ]
