# Generated by Django 5.2.1 on 2025-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subjectstudy_delete_studymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
