# Generated by Django 5.2.1 on 2025-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_simpleuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectstudy',
            name='username',
            field=models.CharField(default='', editable=False, max_length=150, verbose_name='ユーザー名'),
        ),
    ]
